# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0004_auto_20160308_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacompany',
            name='payments_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='observationalstudy',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='correctiv_eurosfueraerzte.Drug', verbose_name='drugs'),
        ),
    ]
