# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 10:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0005_auto_20160622_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512)),
                ('kind', models.SmallIntegerField(choices=[(0, 'Doctors (HCP)'), (1, 'Organisation (HCO)')])),
                ('address', models.CharField(blank=True, max_length=512)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Geographic location')),
                ('first_name', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('unique_country_identifier', models.CharField(blank=True, max_length=255)),
                ('orientations', models.CharField(blank=True, max_length=512)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField()),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'payment recipient',
                'verbose_name_plural': 'payment recipients',
            },
        ),
        migrations.CreateModel(
            name='PharmaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('label', models.CharField(blank=True, choices=[(b'registration_fees', 'registration fees'), (b'travel_accommodation', 'travel & accommodation'), (b'fees', 'fees'), (b'related_expenses', 'related expenses'), (b'donations_grants', 'donations and grants'), (b'sponsorship', 'sponsorship'), (b'research_development', 'Research & development')], max_length=512)),
                ('recipient_kind', models.SmallIntegerField(blank=True, choices=[(0, 'Doctors (HCP)'), (1, 'Organisation (HCO)')], null=True)),
                ('recipient_count', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('pharma_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correctiv_eurosfueraerzte.PharmaCompany')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correctiv_eurosfueraerzte.PaymentRecipient')),
            ],
            options={
                'ordering': ('-amount',),
                'verbose_name': 'pharma payment',
                'verbose_name_plural': 'pharma payments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'medical doctor',
                'proxy': True,
                'verbose_name_plural': 'medical doctors',
            },
            bases=('correctiv_eurosfueraerzte.paymentrecipient',),
        ),
        migrations.CreateModel(
            name='HealthCareOrganisation',
            fields=[
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'healthcare organisation',
                'proxy': True,
                'verbose_name_plural': 'healthcare organisations',
            },
            bases=('correctiv_eurosfueraerzte.paymentrecipient',),
        ),
    ]
