# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0006_doctor_healthcareorganisation_paymentrecipient_pharmapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='name_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pharmapayment',
            name='recipient_detail',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
