# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0007_auto_20160707_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='related_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pharmacompany',
            name='sub_names',
            field=models.TextField(blank=True),
        ),
    ]
