# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0008_auto_20160707_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
