# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0009_paymentrecipient_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='company_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
