# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0010_paymentrecipient_company_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='hidden_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmapayment',
            name='label',
            field=models.CharField(blank=True, choices=[(b'fees', 'fees'), (b'related_expenses', 'related expenses'), (b'registration_fees', 'registration fees'), (b'travel_accommodation', 'travel & accommodation'), (b'donations_grants', 'donations and grants'), (b'sponsorship', 'sponsorship'), (b'research_development', 'Research & development')], max_length=512),
        ),
    ]
