# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0011_auto_20160718_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='origin',
            field=models.CharField(db_index=True, default=b'DE', max_length=2),
        ),
        migrations.AddField(
            model_name='pharmapayment',
            name='currency',
            field=models.CharField(default=b'EUR', max_length=3),
        ),
    ]
