# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0012_auto_20160816_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='total_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='paymentrecipient',
            name='total_euro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pharmapayment',
            name='amount_euro',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pharmapayment',
            name='origin',
            field=models.CharField(db_index=True, default=b'DE', max_length=2),
        ),
    ]
