# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0013_auto_20160816_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacompany',
            name='country',
            field=models.CharField(default=b'DE', max_length=2),
        ),
    ]
