# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0014_pharmacompany_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationalstudy',
            name='slug',
            field=models.SlugField(blank=True, max_length=512),
        ),
    ]
