# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0016_auto_20170203_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroDocSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correctiv_eurosfueraerzte.PharmaPayment')),
            ],
            options={
                'ordering': ('year',),
                'verbose_name': 'Zero Doctor Submission',
                'verbose_name_plural': 'Zero Doctors',
            },
        ),
        migrations.CreateModel(
            name='ZeroDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'female', 'Ms.'), (b'male', 'Mr.')], max_length=20, verbose_name='Mr/Ms')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_sent', models.DateTimeField(blank=True, null=True)),
                ('secret', models.SlugField(max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='address')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name='postcode')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('country', models.CharField(blank=True, choices=[(b'DE', 'Germany'), (b'AT', 'Austria'), (b'CH', 'Switzerland')], max_length=255, verbose_name='country')),
                ('recipient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correctiv_eurosfueraerzte.PaymentRecipient')),
            ],
            options={
                'ordering': ('email_sent',),
                'verbose_name': 'Zero Doctor',
                'verbose_name_plural': 'Zero Doctors',
            },
        ),
        migrations.AddField(
            model_name='zerodocsubmission',
            name='zerodoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correctiv_eurosfueraerzte.ZeroDoctor'),
        ),
    ]
