# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0017_auto_20170317_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zerodocsubmission',
            options={'ordering': ('date',), 'verbose_name': 'Zero Doctor Submission', 'verbose_name_plural': 'Zero Doctors'},
        ),
        migrations.RenameField(
            model_name='zerodocsubmission',
            old_name='year',
            new_name='date',
        ),
        migrations.AddField(
            model_name='zerodocsubmission',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zerodocsubmission',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
