# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0019_zerodoctor_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='is_zerodoc',
            field=models.BooleanField(default=False),
        ),
    ]
