# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0022_auto_20170323_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerodocsubmission',
            name='kind',
            field=models.CharField(choices=[(b'efpia', 'EFPIA Transparency Codex'), (b'observational', 'observational studies')], default=b'efpia', max_length=25),
        ),
    ]
