# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0023_zerodocsubmission_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zerodocsubmission',
            options={'ordering': ('-submitted_on', 'date', 'kind'), 'verbose_name': 'Zero Doctor Submission', 'verbose_name_plural': 'Zero Doctor Submissions'},
        ),
        migrations.AlterModelOptions(
            name='zerodoctor',
            options={'ordering': ('-email_sent',), 'verbose_name': 'Zero Doctor', 'verbose_name_plural': 'Zero Doctors'},
        ),
        migrations.AddField(
            model_name='zerodoctor',
            name='confirmed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
