# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_eurosfueraerzte', '0025_auto_20170621_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecipient',
            name='is_zerodoc',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
